# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFl9a78oX25IUHTQt9L4jiGplCJK4IEs
"""

import pandas as pd
df=pd.DataFrame({'Ism':['Arorbek','Muhsinjon','Ikromjon','Omadjon'],
                 'Familya':['Ubaydullayev','Yusufjonov','Tursunov','Meliqoziyev'],
                 'Yoshi':['19','19','19','20'],
                 'Kursi':['2','2','2','3']
                 })
                print(df)

df.to_excel('hisobot.xlsx', index=False, sheet_name='Sheet')